### ISSUE TITLE
XDG config directories not properly read

### ISSUE THREAD

**Issue by ianseyer** [wacossusca34/glava#1]
Using i3wm on ubuntu Zesty.

When attempting to run `glava --copy-config` I get
```
$ glava --copy-config
'/etc/xdg/xdg-i3:/etc/xdg/glava' does not exist
```

**Comment by r4dixx** [comment]
Same kind of error running Gnome on Ubuntu 17.10:

```
$ glava --copy-config
'/etc/xdg/xdg-ubuntu-xorg:/etc/xdg/xdg-ubuntu-xorg:/etc/xdg/glava' does not exist
```

**Comment by r4dixx** [comment]
OK nevermind. Just had to add `sudo` of course 🙃 Sorry!

**Comment by wacossusca34** [comment]
This command shouldn't require `sudo` being used (actually, the fact that it works with sudo is weird). It's actually a bug with reading the `XDG_CONFIG_DIRS` environment variable. Currently it's not considering that the variable may include multiple XDG config directiories:

```C
#define SHADER_INSTALL_PATH FORMAT("%s/glava", ENV("XDG_CONFIG_DIRS", "/etc/xdg"))
#define SHADER_USER_PATH FORMAT("%s/glava", ENV("XDG_CONFIG_HOME", "%s/.config", ENV("HOME", "/home")))
```
and then `SHADER_INSTALL_PATH` is errornously read as a path to a single directory.

**Comment by wacossusca34** [comment]
Sorry about the wait, I fixed this just by changing `SHADER_INSTALL_PATH` to `"/etc/xdg/glava"`, since that is where it always installs to via the makefile. I will probably change this later to use a macro that is set within the makefile when installing, but right now I don't see this causing any issues.

**Comment by r4dixx** [comment]
Works well now :) Thanks for the fix!
