### ISSUE TITLE
GLava fails to load function pointers on RPM distros due to missing 'libglvnd-devel' dependency

### ISSUE THREAD

**Issue by banancc** [wacossusca34/glava#100]
Please help me!
![ekranattels no 2019-02-22 21-32-07](https://user-images.githubusercontent.com/47900972/53266427-69187080-36e9-11e9-8fe8-1236224fa917.png)
![ekranattels no 2019-02-22 21-33-59](https://user-images.githubusercontent.com/47900972/53266523-a54bd100-36e9-11e9-91aa-9b5b7bf07f89.png)

**Comment by coderobe** [comment]
how did you install glava? do you have libGL and libGLX available?

**Comment by wacossusca34** [comment]
The output of `ls -l /usr/lib | grep libGL` would be helpful here.

**Comment by Kolato** [comment]
Same issue on openSUSE tumbleweed, installed from the official repositories.

This is the return of `ls -l /usr/lib | grep libgl`:

`lrwxrwxrwx   1 root root       17 Feb  4 21:33 libglapi.so.0 -> libglapi.so.0.0.0
-rwxr-xr-x   1 root root   118528 Feb  4 21:33 libglapi.so.0.0.0
lrwxrwxrwx   1 root root       23 Feb  6 16:13 libglib-2.0.so.0 -> libglib-2.0.so.0.5800.3
-rwxr-xr-x   1 root root  1285120 Feb  6 16:13 libglib-2.0.so.0.5800.3
`

**Comment by wacossusca34** [comment]
@Kolato the `grep libGL` part is case sensitive. Please run the command _exactly_ as I specified: `ls -l /usr/lib | grep libGL`.

Usually the problem is needing to run `ldconfig`. I'm not sure why some systems do not have a symlink for `libGL.so`, but it seems like most bindings attempt to load from `libGL.so.1` as well, so I may add that in.

(also, `libGLX` usually does not need to exist as most implementations contain the GLX functions in `libGL`)

**Comment by Kolato** [comment]
My bad sorry - Here is the return of `ls -l /usr/lib | grep libGL`:

```lrwxrwxrwx   1 root root       22 Jan 30 01:13 libGLdispatch.so.0 -> libGLdispatch.so.0.0.0
-rwxr-xr-x   1 root root   329356 Jan 30 01:13 libGLdispatch.so.0.0.0
lrwxrwxrwx   1 root root       21 Jan 30 01:13 libGLESv1_CM.so.1 -> libGLESv1_CM.so.1.2.0
-rwxr-xr-x   1 root root    38456 Jan 30 01:13 libGLESv1_CM.so.1.2.0
lrwxrwxrwx   1 root root       18 Jan 30 01:13 libGLESv2.so.2 -> libGLESv2.so.2.1.0
-rwxr-xr-x   1 root root    63028 Jan 30 01:13 libGLESv2.so.2.1.0
lrwxrwxrwx   1 root root       14 Jan 30 01:13 libGL.so.1 -> libGL.so.1.7.0
-rwxr-xr-x   1 root root   431668 Jan 30 01:13 libGL.so.1.7.0
lrwxrwxrwx   1 root root       15 Jan 30 07:33 libGLU.so.1 -> libGLU.so.1.3.1
-rwxr-xr-x   1 root root   501508 Jan 30 07:33 libGLU.so.1.3.1
lrwxrwxrwx   1 root root       16 Feb  4 21:33 libGLX_indirect.so.0 -> libGLX_mesa.so.0
lrwxrwxrwx   1 root root       20 Feb  4 21:33 libGLX_mesa.so -> libGLX_mesa.so.0.0.0
lrwxrwxrwx   1 root root       20 Feb  4 21:33 libGLX_mesa.so.0 -> libGLX_mesa.so.0.0.0
-rwxr-xr-x   1 root root   498308 Feb  4 21:33 libGLX_mesa.so.0.0.0
lrwxrwxrwx   1 root root       15 Jan 30 01:13 libGLX.so.0 -> libGLX.so.0.0.0
-rwxr-xr-x   1 root root    75432 Jan 30 01:13 libGLX.so.0.0.0
```

**Comment by banancc** [comment]
> how did you install glava? do you have libGL and libGLX available?

![ekranattels no 2019-02-23 17-36-25](https://user-images.githubusercontent.com/47900972/53288511-94569a80-3791-11e9-9041-d6dcfd505003.png)

How to check libGL and libGLX?

**Comment by banancc** [comment]
> ls -l /usr/lib | grep libGL

![ekranattels no 2019-02-23 17-40-01](https://user-images.githubusercontent.com/47900972/53288550-1941b400-3792-11e9-8b43-26a12e00ac1b.png)

**Comment by banancc** [comment]
```
[qwerty@abc ~]$ ldconfig
ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
```


> @Kolato the `grep libGL` part is case sensitive. Please run the command _exactly_ as I specified: `ls -l /usr/lib | grep libGL`.
> 
> Usually the problem is needing to run `ldconfig`. I'm not sure why some systems do not have a symlink for `libGL.so`, but it seems like most bindings attempt to load from `libGL.so.1` as well, so I may add that in.
> 
> (also, `libGLX` usually does not need to exist as most implementations contain the GLX functions in `libGL`)

**Comment by wacossusca34** [comment]
I did some digging and found out that **some packages for RPM based distros do not create an soname link without a version for dynamic/compiler linking** (ie. `libglvnd-glx` on Fedora). For whatever obscure reason, **'linker-name' symlinks are provided by the `-devel` packages**.

So, let's resolve this:

@Kolato **install `libglvnd-devel`**.

@banancc `ls -l /usr/lib | grep libGL` _should not return nothing_. Re-install all opengl libraries, and install `libglvnd-devel`.

@jubalh please manually require `libglvnd-devel` as a _runtime requirement_. The build system is not able to detect runtime dependencies accessed via `dlopen`.

I can patch GLava to also attempt to read from the versioned libraries beforehard if that is considered a better fix (afaik any standards on the versioning used via `dlopen` isn't well-defined). In this case, @jubalh, a `libglvnd` dependency should be added.

**Comment by jubalh** [comment]
@wacossusca34 Okay. It's on it's [way](https://build.opensuse.org/request/show/678520) into Factory. Devel project already contains it.
