### ISSUE TITLE
Undefined behavior in circle shader

### ISSUE THREAD

**Issue by coderobe** [wacossusca34/glava#105]
While looking into a different issue, I noticed some noise in the center of the `circle` shader on one of my machines, which also happens to behave differently depending on the driver/gpu used.

i915 (Intel UHD Graphics 630)
![image](https://user-images.githubusercontent.com/8442384/54206598-eb21db00-44d8-11e9-8de0-2ca1e314c774.png)

nouveau (NVIDIA GeForce GTX 1070 Mobile)
![image](https://user-images.githubusercontent.com/8442384/54206853-684d5000-44d9-11e9-9ee4-00313ee2add1.png)

The noise is predictable, and correlates with the rest of the shader spikes.

I cannot reproduce this with other shaders.

**Comment by coderobe** [comment]
Given that this happens on both intel and nouveau i'm assuming it's *not* a driver bug. Still looking into it.

**Comment by coderobe** [comment]
Isolated it to the first shader pass

**Comment by coderobe** [comment]
#106 fixes the issue

![image](https://user-images.githubusercontent.com/8442384/54211238-435cdb00-44e1-11e9-840a-5b6c26b234d5.png)

**Comment by wacossusca34** [comment]
Intel HD graphics strike again!
