### ISSUE TITLE
Can i change visualizer sensitivity?

### ISSUE THREAD

**Issue by banancc** [wacossusca34/glava#108]

**Comment by wacossusca34** [comment]
Amplitude (increasing will make the visualizer 'higher'):
https://github.com/wacossusca34/glava/blob/master/shaders/bars.glsl#L13
Averaging frames (reducing increases responsiveness):
https://github.com/wacossusca34/glava/blob/master/shaders/smooth_parameters.glsl#L56
Sampling mode (setting to `hybrid` or `maximum` will improve responsiveness and accuracy):
https://github.com/wacossusca34/glava/blob/master/shaders/smooth_parameters.glsl#L30

GLava is _very_ configurable, but this also means you need to experiment with inputs to get your desired effect. The commentary in the root config directory should be extensive enough to point you to the values you wish to change -- please read it.
