### ISSUE TITLE
Testing on Solus 3

### ISSUE THREAD

**Issue by Riokei** [wacossusca34/glava#11]
![peek 2018-02-05 09-56](https://user-images.githubusercontent.com/16841390/35811962-bf9f0f18-0a5d-11e8-9dfe-26d67ff639b2.gif)
The above gif is basically the issue, I tried xroot and normal on solus (still on GLFW 3.2 so I can't test 3.3 features yet) Any idea what could be causing another background to be shown instead of my actual wallpaper?

**Comment by wacossusca34** [comment]
Strange! It looks like you have two wallpapers.

GLava simply reads from the root X11 window to copy the wallpaper via `xroot`. It looks like your window manager actually creates another window for the wallpaper instead of drawing on the root window, which is unusual.

You can work around this using GLFW 3.3 and `"native"` transparency at the moment, but I can also work on a Solus-specific fix.

**Comment by Riokei** [comment]
I see! I'll have to wait til solus updates GLFW 3.3 to try that then. That really is quite interesting though.

**Comment by wacossusca34** [comment]
You'll probably want to compile GLFW 3.3 yourself. It's not even one of GLFW's release builds at the moment.

It also wouldn't be too difficult to imlement a fix for Budgie Desktop (WM for Solus). I just would need to get it running in my container to see what exactly is going on here with desktop backgrounds.

**Comment by Riokei** [comment]
Okay I'll give compiling it a try soon sorry been a bit busy.

**Comment by wacossusca34** [comment]
Can you paste the output of running `xprop` and `xwininfo` in a terminal and clicking your desktop background? It would prevent me from having to install budgie myself on an unsupported distro.

**Comment by Riokei** [comment]
`shadow@socrates ~ $ xprop
WM_NAME(STRING) = "mutter guard window"
`

`shadow@socrates ~ $ xwininfo

xwininfo: Please select the window about which you
          would like information by clicking the
          mouse in that window.

xwininfo: Window id: 0x1c0002f "mutter guard window"

  Absolute upper-left X:  0
  Absolute upper-left Y:  0
  Relative upper-left X:  0
  Relative upper-left Y:  0
  Width: 1920
  Height: 1080
  Depth: 0
  Visual: 0x21
  Visual Class: TrueColor
  Border width: 0
  Class: InputOnly
  Colormap: 0x0 (not installed)
  Bit Gravity State: ForgetGravity
  Window Gravity State: NorthWestGravity
  Backing Store State: NotUseful
  Save Under State: no
  Map State: IsViewable
  Override Redirect State: yes
  Corners:  +0+0  -0+0  -0-0  +0-0
  -geometry 1920x1080+0+0

`

**Comment by wacossusca34** [comment]
I guess that makes this related to issue #18

**Comment by wacossusca34** [comment]
I'm still toying around with this, but if you have time please test the `unstable` branch as the above commit may have fixed the issue.

**Comment by wacossusca34** [comment]
This is the same issue as #18. As a temporary fix you can set the same wallpaper to the root background as well using something like `feh`. `native` transparency will also work.

Merging with #18, and closing this now.
