### ISSUE TITLE
'radial' inverted by default

### ISSUE THREAD

**Issue by Hideman85** [wacossusca34/glava#111]
Hello,

I just see that the radial vizualizer the sounds (right/letf) is inverted:

![Proof](https://user-images.githubusercontent.com/16165119/54492122-13884b80-48c4-11e9-89be-6cb449abf035.png)

Try yourself: https://www.youtube.com/watch?v=1SbJc7W0-JI

![Left](https://user-images.githubusercontent.com/16165119/54492213-da041000-48c4-11e9-86f9-e264e67b6e9b.png)

**Comment by wacossusca34** [comment]
In `radial.glsl` there is `#define INVERT 0` which you can change between `1` and `0`.

However it looks like the default _is_ inverted, which I did not notice! I will fix this in a later release.

**Comment by Hideman85** [comment]
I don"t take a look to radial.glsl but only rc.glsl.
But it work nice thank you!
