### ISSUE TITLE
is there a way to have glava below nemo-desktop?

### ISSUE THREAD

**Issue by Pitigoi** [wacossusca34/glava#114]
??

**Comment by wacossusca34** [comment]
Set the desktop layer (not the root window, but the X window for the icons themselves) to use the `above` hint using `wmctrl`. Alternatively you can tell GLava to go below instead, using `#request addxwinstate "below"`.

**Comment by Pitigoi** [comment]
apparently, on linux mint, you can toggle the desktop icons with
`gsettings set org.nemo.desktop show-desktop-icons false`
and suddenly the icons are above
