### ISSUE TITLE
Simple Menu shortcuts for GLava

### ISSUE THREAD

**Issue by SaucySauce** [wacossusca34/glava#115]
I made a couple .desktop files for ease of reach to start and stop GLava. By default it uses 'glava --desktop'. Kills process with 'pkill glava'.
Don't know if you plan to add more GUI friendly options but here you have a couple already set if you'd like to use. Insert _I know it ain't much but it's honest work_ meme.

https://gitlab.com/SaucySauce/glava-app-launchers/tree/master

**Comment by coderobe** [comment]
Seems like i cannot view that repository without signing up for that site.

Besides that, i don't think a .desktop file that pkills glava makes much sense...
