### ISSUE TITLE
Build progress is complicated

### ISSUE THREAD

**Issue by hungpham2411** [wacossusca34/glava#116]
Hi,
Firstly, thanks for making this tool, I searched this kind of tool for a long time but the errors on build progress make me disappointment.
I'm using Ubuntu 18.04 so I install all requirements as installing guide mentioned, then I start to build.
- Run `CFLAGS="-march=native" meson build` throws error `C library 'GL' not found`. Installing libgl1-mesa-dev fixed that. OK
- Run `ninja -C build` throws error `fatal error: sys/cdefs.h: No such file or directory`. Googled for error then I installed `g++-multilib` but error stills there, can't do anything anymore.

The point is build progress requires installation ton of libs, people take much of time for searching after each lib/file missing (even that I'm still fail to install). So, as an ordinary user I hope you can make the installation easier.
Thanks!

**Comment by coderobe** [comment]
it's not actually a ton of libs, ubuntu just likes to make things complicated by splitting every project into 5 different packages.

sys/cdefs.h is part of glibc, which you should have.

**Comment by coderobe** [comment]
the first google result for "cdefs.h ubuntu" does point to `libc6-dev`, so it appears like ubuntu has also split that from (g)libc itself. Either way, that's the package you want.

note that `build-essential` - the metapackage that you should've installed if you intend to build anything, according to ubuntu, does contain that.
