### ISSUE TITLE
Compile Issues on OSX

### ISSUE THREAD

**Issue by panda2k** [wacossusca34/glava#12]
When building with make INSTAL=osx I get `IEC 60559 standard unsupported on target system`.

**Comment by wacossusca34** [comment]
OSX has a range of issues with GLava at the moment, the primary one being that it has a hard dependency on pulseaudio. This seems to be a compiler hiccup that is probably fixable, but you will run into more issues if I resolve that.

At the moment, I need either an OSX installation myself or another contributor to get GLava working on OSX. I will revisit this issue, but I will not be fixing it in the near future.
