### ISSUE TITLE
Implementing uniform float time

### ISSUE THREAD

**Issue by faazuthnar** [wacossusca34/glava#120]
Hi there, glava is a superior visualization tool, I love it.
Anyways, I started to dig in a little and create a custom fragment shader. And I ran into a problem. `uniform float time;` or `u_time`, neither work. It would be nice to have a time variable to simply be able to do animations apart from sampling audio.
Or am I missing something? I'm not very familiar with shaders. Thanks in advance.

**Comment by faazuthnar** [comment]
Dug a little further and implemented it.

**Comment by matyklugDebbuged** [comment]
i would like to implement that as well. what would i do?
