### ISSUE TITLE
Feature Request: add a setting to only use half the spectrum for bars

### ISSUE THREAD

**Issue by joshuah345** [wacossusca34/glava#123]
this would be the same as providing a mono output instead of stereo

**Comment by swiftlysstuff** [comment]
bump

**Comment by swiftlysstuff** [comment]
I also think this should be added for people who prefer a look similar to the extremely overdone Monstercat Visualizer style

**Comment by wacossusca34** [comment]
I will get around to this later. Keep in mind that PRs are always welcome, especially as I am preoccupied by other things nowadays.
