### ISSUE TITLE
Question about mpd config

### ISSUE THREAD

**Issue by vaskark** [wacossusca34/glava#124]
Hi. I followed the instructions and added

```
audio_output {
    type                    "fifo"
    name                    "GLava"
    path                    "/tmp/mpd.fifo"
    format                  "22050:16:2"
}
```
to my ./config/mpd/mpd.conf file. But I already have a block of code there:

```
audio_output {
       type      "fifo"
       name      "Visualizer feed"
       path       "/tmp/mpd.fifo"
       format     "44100:16:2"
}
```

So do I delete this original block? I assume I do.

Also, when I run GLava with audio=fifo it seems to react differently from when I don't use that flag option (just the usual glava --desktop). Is this normal?

I'm running latest glava from git on Ubuntu 19.04.
Thanks. Great app, btw.

**Comment by wacossusca34** [comment]
I assume you already have that from running cava or similar software. All that matters is the path and format. If for some reason you would like to use both you can set the source in GLava to a different path.
