### ISSUE TITLE
A small height leads to cut off bars

### ISSUE THREAD

**Issue by cwrau** [wacossusca34/glava#125]
I use the default `rc.glsl` config except:

```
#request setopacity "xroot"
#request setgeometry 0 0 2560 20
#request setxwintype "!-"
```

Everything works, but the bars are cut off:
![image](https://user-images.githubusercontent.com/14326070/62134088-326e0400-b2e0-11e9-9ffd-39fefdf433ff.png)

Do I have to change something? Maybe in the bars.glsl?

**Comment by coderobe** [comment]
You can try tuning the amplification in bars.glsl: https://github.com/wacossusca34/glava/blob/f1284a68351733699f3337bc483608bf7a5f5ac0/shaders/glava/bars.glsl#L11

**Comment by cwrau** [comment]
Oh, I guess I should have tried more, I set it from 300 to 200 and to 100.
Didn't see anything change 😅

Thanks for the quick response!
