### ISSUE TITLE
Setting opacity documentation?

### ISSUE THREAD

**Issue by mike391** [wacossusca34/glava#127]
How do I configure opacity on bars? There is no documentation that clearly states how to do this.  There is `#define USE_ALPHA` but no clear indication of what values it takes and if thats what it does. 

 I want to set the opacity of the bars mod so that my wallpaper shows through a bit, im on budgie if that matters.

**Comment by wacossusca34** [comment]
The confusion comes from an error on my part, apparently I did not commit a premultiply step into `bars` and `graph`, which should be there.

Ideally you have the following stage (`2.frag`) for the `bars` module:

```GLSL
#if USE_ALPHA == 0
#error __disablestage
#endif

#include ":util/premultiply.frag"
```

Where having `USE_ALPHA` set to `1` ensures the premultiply step is included. This has a minor performance penalty, hence the option to explicitly enable it if transparency colors are defined in `bars.glsl`.

To _actually set_ transparent colors, you only need to add transparent bits onto the end of colors in any module config, for example `#FF000070` is a _mostly_ transparent bright red. If the alpha bits are omitted, then they are assumed to be `FF` (fully opaque). Alternatively, the final floating point value in a `vec4` also corresponds to the alpha bits.

**Comment by wacossusca34** [comment]
Since you pointed out the documentation being unclear from the comments/syntax, I added a section to the wiki: ["Working with colors"](https://github.com/wacossusca34/glava/wiki#working-with-colors)
