### ISSUE TITLE
[Gnome] How to hide glava in activities tab?

### ISSUE THREAD

**Issue by Dizeeee** [wacossusca34/glava#14]
Basically the title, is there currently a way to hide glava while using the activities tab? It's not the end of the world but still is a little annoying.

**Comment by wacossusca34** [comment]
"activities tab"? I'm assuming you are talking about GNOME.

Try using `#request addxwinstate "skip_taskbar"` and `#request addxwinstate "skip_pager"` in your `rc.glsl` file.

**Comment by wacossusca34** [comment]
Closing, unless @Dizeeee indicates that the issue persist.
