### ISSUE TITLE
Configurable solid background color

### ISSUE THREAD

**Issue by Madkita** [wacossusca34/glava#16]
since transparent doesn't work with any of glfw versions I tried, is there a way to change the background color from the usual black color to something like solarized

**Comment by wacossusca34** [comment]
If `#request setopacity "xroot"` does not work, that is a bug. `"native"` needs GLFW 3.3+ _and_ an X11 compositor that supports window transparency (ie. compton).

Your feature request for solid background colors is also easily doable. I will add a commit for that today.

**Comment by wacossusca34** [comment]
For issues with `#request setopacity`, please create a separate issue with more information.

**Comment by wacossusca34** [comment]
Feature has been added to the `unstable` branch and will be part of GLava 1.2.

**Comment by Madkita** [comment]
wow that was very fast 
i do have `#request setopacity` set to xroot and libxext installed am running kde plasma 5.11.5 and there is no transparency that's why i choose to go with a solid color

**Comment by wacossusca34** [comment]
@Madkita issues with KWin (KDE) should go in issue #4. There are a few issues with KDE right now, but at the very least transparency should be working. Can you post a link to your full `rc.glsl` and details there?
