### ISSUE TITLE
Cannot run ninja -C build

### ISSUE THREAD

**Issue by NEjjjO** [wacossusca34/glava#214]
Cannot run ninja -C build - gives fatal error
X11-extensions-xcomposite.h: no such file or directory

**Comment by HumanG33k** [comment]
do you install the libxcomposite-dev package ? or your distribution alternative ?

**Comment by BaigHack3rss** [comment]
I have the same issue even with the package installed

**Comment by HumanG33k** [comment]
Can you send more information about your operating system, version of packages, etc.
Also you can check my modified version a little more ready to use : 
https://gitlab.com/wild-turtles-publicly-release/glava/glava 

Feel free to come back here to comment but be sure of quote me for a little more fast feedback.

**Comment by BaigHack3rss** [comment]
> Can you send more information about your operating system, version of packages, etc. Also you can check my modified version a little more ready to use : https://gitlab.com/wild-turtles-publicly-release/glava/glava
> 
> Feel free to come back here to comment but be sure of quote me for a little more fast feedback.

Thankyou for the gitlab repo it worked

**Comment by HumanG33k** [comment]
Your welcome.
