### ISSUE TITLE
2 colors at each bar?

### ISSUE THREAD

**Issue by scorpium959** [wacossusca34/glava#222]
i changed the color of the bars, from that i had an idea, can i put 2 colors in the bar? Like:
![Captura de pantalla de 2022-01-04 16-45-56](https://user-images.githubusercontent.com/64052400/148115548-0eab6e4b-0c08-4709-9527-41089dc2cc5d.png)
the part more taller have a color and it changes until reaching the base which will be purple maybe, the thing is to make a gradient transition between the 2 colors.

**Comment by JacksonWrath** [comment]
You can! 

Open `~/.config/glava/bars.glsl` and look for these lines:
```
/* Bar color changes with height */
#define GRADIENT (d / GRADIENT_POWER + 1)
/* Bar color */
#define COLOR (#3366b2 * GRADIENT)
```

Change them to something like this:
```
/* Bar color changes with height */
#define GRADIENT (d / AREA_HEIGHT)
/* Bar color */
#define LOW_COLOR #f542ff
#define HIGH_COLOR #33c2ff
#define COLOR mix(LOW_COLOR, HIGH_COLOR, GRADIENT)
```
`mix` interpolates between the two colors. The 3rd parameter is a percentage (0.0 - 1.0), so I changed `GRADIENT` to be a fraction of GLava's window height. You can adjust `GRADIENT` to tweak how and where it transitions. Increasing/decreasing `d` by some constant will shift the gradiant up and down, for example.

**Comment by scorpium959** [comment]
> You can!
> 
> Open `~/.config/glava/bars.glsl` and look for these lines:
> 
> ```
> /* Bar color changes with height */
> #define GRADIENT (d / GRADIENT_POWER + 1)
> /* Bar color */
> #define COLOR (#3366b2 * GRADIENT)
> ```
> 
> Change them to something like this:
> 
> ```
> /* Bar color changes with height */
> #define GRADIENT (d / AREA_HEIGHT)
> /* Bar color */
> #define LOW_COLOR #f542ff
> #define HIGH_COLOR #33c2ff
> #define COLOR mix(LOW_COLOR, HIGH_COLOR, GRADIENT)
> ```
> 
> `mix` interpolates between the two colors. The 3rd parameter is a percentage (0.0 - 1.0), so I changed `GRADIENT` to be a fraction of GLava's window height. You can adjust `GRADIENT` to tweak how and where it transitions. Increasing/decreasing `d` by some constant will shift the gradiant up and down, for example.

**Comment by scorpium959** [comment]
@JacksonWrath i dont know but the code doesnt work what i have to do?
i copied the code but the result isnt like i wanted, the only color that is present is the low color but not the high.

**Comment by scorpium959** [comment]
Update, i got it work:
`/* Bar color changes with height */
#define GRADIENT (d / GRADIENT_POWER)
/* Bar color */
#define LOW_COLOR #f542ff
#define HIGH_COLOR #33c2ff
#define COLOR mix(LOW_COLOR, HIGH_COLOR, GRADIENT)`

i had to change the AREA_HEIGHT constant to GRADIENT_POWER and it works now.

@JacksonWrath Thanks for the help :)

**Comment by JacksonWrath** [comment]
I'm glad you got something working! I think that happened because I forgot that I disabled the `setgeometry` line in rc.glsl and am just enforcing the window size with KDE. The `AREA_HEIGHT` might be different than what is actually being drawn or something.

Either way, you got the gist. You're welcome!
