### ISSUE TITLE
Issue with bspwm and multiple monitors

### ISSUE THREAD

**Issue by nautilor** [wacossusca34/glava#225]
I have a dual monitor setup with bspwm

I have configured a bspwm rule like this
```bash
bspc rule -a GLava state=floating layer=below sticky=true locked=true border=off focus=off center=true follow=off rectangle=1920x1080+0+0
```
so that glava will stay below all the programs.

Since I have multiple monitors I have this keybinding in my sxhkd config

```
super + shift + {Left,Down,Up,Right}
    dir={west,south,north,east}; \
    bspc node -s "$dir.local" --follow \
	|| bspc node -m "$dir" --follow
```

with this, I can move window from one monitor to another but when running glava this behavior does not work anymore

[Demo video](https://streamable.com/khmq9f)

as you can see in the video I can move the windows between monitors without any problem but it's not possible when glava is running

**Comment by HumanG33k** [comment]
Do you have any log ? in the glava output or in  ~/.xerror (or whatever) ?
