### ISSUE TITLE
build issues

### ISSUE THREAD

**Issue by BaigHack3rss** [wacossusca34/glava#226]
Hi there i am having issues with building from source I am using kali linux on desktop.

Here is my terminal log: 

ninja: Entering directory `build'
[1/10] Compiling C object glava.p/glava-cli_cli.c.o
cc1: warning: command-line option ‘-std=c++11’ is valid for C++/ObjC++ but not for C
[2/10] Linking target libglava.so
FAILED: libglava.so 
cc  -o libglava.so libglava.so.p/glava_glfw_wcb.c.o libglava.so.p/glava_glava.c.o libglava.so.p/glava_render.c.o libglava.so.p/glava_xwin.c.o libglava.so.p/glava_glad.c.o libglava.so.p/glava_fifo.c.o libglava.so.p/glava_glx_wcb.c.o libglava.so.p/glava_glsl_ext.c.o libglava.so.p/glava_pulse_input.c.o -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -Wl,-soname,libglava.so -pthread -lpulse -lpulse-simple -ldl -lm -lX11 -lXext -lXrender -Wl,--end-group
/usr/bin/ld: libglava.so.p/glava_render.c.o:(.bss+0x20): multiple definition of `glava_abort'; libglava.so.p/glava_glava.c.o:(.data.rel+0x8): first defined here
/usr/bin/ld: libglava.so.p/glava_render.c.o:(.bss+0x18): multiple definition of `glava_return'; libglava.so.p/glava_glava.c.o:(.data.rel+0x0): first defined here
/usr/bin/ld: libglava.so.p/glava_xwin.c.o:(.bss+0x8): multiple definition of `glava_abort'; libglava.so.p/glava_glava.c.o:(.data.rel+0x8): first defined here
/usr/bin/ld: libglava.so.p/glava_xwin.c.o:(.bss+0x0): multiple definition of `glava_return'; libglava.so.p/glava_glava.c.o:(.data.rel+0x0): first defined here
/usr/bin/ld: libglava.so.p/glava_glx_wcb.c.o:(.bss+0x58): multiple definition of `glava_abort'; libglava.so.p/glava_glava.c.o:(.data.rel+0x8): first defined here
/usr/bin/ld: libglava.so.p/glava_glx_wcb.c.o:(.bss+0x50): multiple definition of `glava_return'; libglava.so.p/glava_glava.c.o:(.data.rel+0x0): first defined here
/usr/bin/ld: libglava.so.p/glava_glsl_ext.c.o:(.bss+0x8): multiple definition of `glava_abort'; libglava.so.p/glava_glava.c.o:(.data.rel+0x8): first defined here
/usr/bin/ld: libglava.so.p/glava_glsl_ext.c.o:(.bss+0x0): multiple definition of `glava_return'; libglava.so.p/glava_glava.c.o:(.data.rel+0x0): first defined here
collect2: error: ld returned 1 exit status
[3/10] Compiling C++ object libglfft.a.p/glfft_glfft_gl_interface.cpp.o
FAILED: libglfft.a.p/glfft_glfft_gl_interface.cpp.o 
c++ -Ilibglfft.a.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -O2 -DGLAVA_UNIX -DGLAVA_GLX '-DGLAVA_VERSION="v1.6.3-90-g6fc0e32"' '-DSHADER_INSTALL_PATH="/etc/xdg/glava"' '-DGLAVA_RESOURCE_PATH="/usr/share/glava/resources"' -fPIC -MD -MQ libglfft.a.p/glfft_glfft_gl_interface.cpp.o -MF libglfft.a.p/glfft_glfft_gl_interface.cpp.o.d -o libglfft.a.p/glfft_glfft_gl_interface.cpp.o -c ../glfft/glfft_gl_interface.cpp
In file included from ../glfft/glfft_gl_interface.cpp:19:
../glfft/glfft_gl_interface.hpp: In function ‘void glfft_log(const char*, ...)’:
../glfft/glfft_gl_interface.hpp:43:14: error: ‘stdout’ was not declared in this scope
   43 |     vfprintf(stdout, fmt, l);
      |              ^~~~~~
../glfft/glfft_gl_interface.hpp:33:1: note: ‘stdout’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
   32 |     #include <error.h>
  +++ |+#include <cstdio>
   33 | }
../glfft/glfft_gl_interface.hpp:43:5: error: ‘vfprintf’ was not declared in this scope; did you mean ‘vwprintf’?
   43 |     vfprintf(stdout, fmt, l);
      |     ^~~~~~~~
      |     vwprintf
../glfft/glfft_gl_interface.hpp: In function ‘double glfft_time()’:
../glfft/glfft_gl_interface.hpp:54:17: error: ‘stderr’ was not declared in this scope
   54 |         fprintf(stderr, "clock_gettime(CLOCK_REALTIME, ...): %s\n", strerror(errno));
      |                 ^~~~~~
../glfft/glfft_gl_interface.hpp:54:17: note: ‘stderr’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
../glfft/glfft_gl_interface.hpp:54:78: error: ‘errno’ was not declared in this scope
   54 |         fprintf(stderr, "clock_gettime(CLOCK_REALTIME, ...): %s\n", strerror(errno));
      |                                                                              ^~~~~
../glfft/glfft_gl_interface.hpp:33:1: note: ‘errno’ is defined in header ‘<cerrno>’; did you forget to ‘#include <cerrno>’?
   32 |     #include <error.h>
  +++ |+#include <cerrno>
   33 | }
../glfft/glfft_gl_interface.hpp:54:9: error: ‘fprintf’ was not declared in this scope; did you mean ‘wprintf’?
   54 |         fprintf(stderr, "clock_gettime(CLOCK_REALTIME, ...): %s\n", strerror(errno));
      |         ^~~~~~~
      |         wprintf
../glfft/glfft_gl_interface.cpp: In member function ‘virtual void GLFFT::GLContext::log(const char*, ...)’:
../glfft/glfft_gl_interface.cpp:201:5: error: ‘vsnprintf’ was not declared in this scope; did you mean ‘vswprintf’?
  201 |     vsnprintf(buffer, sizeof(buffer), fmt, va);
      |     ^~~~~~~~~
      |     vswprintf
[5/10] Compiling C++ object libglfft.a.p/glfft_glfft_wisdom.cpp.o
FAILED: libglfft.a.p/glfft_glfft_wisdom.cpp.o 
c++ -Ilibglfft.a.p -I. -I.. -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wnon-virtual-dtor -O2 -DGLAVA_UNIX -DGLAVA_GLX '-DGLAVA_VERSION="v1.6.3-90-g6fc0e32"' '-DSHADER_INSTALL_PATH="/etc/xdg/glava"' '-DGLAVA_RESOURCE_PATH="/usr/share/glava/resources"' -fPIC -MD -MQ libglfft.a.p/glfft_glfft_wisdom.cpp.o -MF libglfft.a.p/glfft_glfft_wisdom.cpp.o.d -o libglfft.a.p/glfft_glfft_wisdom.cpp.o -c ../glfft/glfft_wisdom.cpp
../glfft/glfft_wisdom.cpp: In member function ‘std::pair<double, GLFFT::FFTOptions::Performance> GLFFT::FFTWisdom::study(GLFFT::Context*, const GLFFT::WisdomPass&, GLFFT::FFTOptions::Type) const’:
../glfft/glfft_wisdom.cpp:273:23: error: ‘logic_error’ was not declared in this scope
  273 |                 throw logic_error("Invalid input mode.\n");
      |                       ^~~~~~~~~~~
../glfft/glfft_wisdom.cpp:307:23: error: ‘logic_error’ was not declared in this scope
  307 |                 throw logic_error("Invalid output mode.\n");
      |                       ^~~~~~~~~~~
ninja: build stopped: subcommand failed.

**Comment by preetamsad** [comment]
Did u solve it? I am getting the same issue.

**Comment by BaigHack3rss** [comment]
> Did u solve it? I am getting the same issue.

I did. use the gitlab repo to build glava
