### ISSUE TITLE
Bspwm works, with a few tweaks.

### ISSUE THREAD

**Issue by Toshimonster** [wacossusca34/glava#24]
I can confirm that GLava works on BSPWM as intended, however it requires a bit of configuration;

A Rule, or someother method requires the following variables to be set:
`state=floating layer=below sticky=true locked=true border=off`

Then, a program will have to be used to change the geometry of the window around (0,0); with the width and hieght that of the screen resolution. Anything above the screen resolution will make GLava become fully black.

I use `wmctrl`.

A external rule can be used to set all of this everytime GLava is ran.

I expect i3 could also be successfully used through the same sort of configuration.

Im writing this for a enhancement in the readme, and the wiki, and perhaps a method for automatically configuring it in the future.

**Comment by wacossusca34** [comment]
GLava has options that allow you to do most of this:

```GLSL
#request addxwinstate "floating"
#request addxwinstate "below"
#request addxwinstate "sticky"
#request setdecorated false
```

As for `locked=true`, I'm not really sure what you are referring to. GLava has `setforcegeometry`, but that is a hack which periodically repositions the window in case the WM repositions it (ie. at startup, workspace changes, etc), so perhaps it does something similar?

> Then, a program will have to be used to change the geometry of the window around (0,0); with the width and hieght that of the screen resolution. Anything above the screen resolution will make GLava become fully black.

This is a quirk of the `"xroot"` style transparency. Use `"native"` if you don't want to encounter this issue.

> I expect i3 could also be successfully used through the same sort of configuration.

i3 blatantly does not support desktop window types, so I won't bother even trying to get it to work if i3(-gaps) developers aren't interested in providing the minimal support needed on their behalf.

> ... and perhaps a method for automatically configuring it in the future.

I'm intersted in doing something like this within GLava with a 'smart desktop' window setting that behaves according to the underlying WM. I first want to deal with remaining WM compatibility issues though (ie. KDE).

**Comment by Toshimonster** [comment]
Hrm, after testing the commands given above, They fail; addxwinstate is not a valid command, thus i tried it with setxwinstate ~ however that made that application revert to its original state ~ as if it is a normal application. setforcegeometry also seems to have no effect.

**Comment by wacossusca34** [comment]
Please output the contents of `glava --version`. `setxwinstate` is actually not a valid command, and `addxwinstate` certainly is, unless you have an old build of glava.

`setforcegeometry` is really just a niche setting that I don't think anyone else except for myself (with my weird WM and layout). As I mentioned before, it doesn't actually change the window class/behaviour, rather it just periodically repositions the window in case the WM moves it.

**Comment by wacossusca34** [comment]
@Toshimonster it would be nice to have a response on this issue, otherwise I will close it.

**Comment by Toshimonster** [comment]
@wacossusca34 Sorry - it seems i didnt get a notification for your previous comment. I have upgraded my system since, and while testing, addxwinstate is now a valid command. 
I have also transitioned into wayland, and i can confirm that glava seems to work just fine in xwayland, yet it does not read the wallpaper. Perhaps a feature for a manual image to be set as a background might be appreciated, as one can scot the background.

glava version is not 1.4.1; I dont know the version prior.

**Comment by wacossusca34** [comment]
@Toshimonster I'm surprised GLava even works with XWayland. Xroot not working is to be expected, and I have expressed disinterest in trying to port it for wayland compositors due to relevant protocols not being standardized.

I need you to try running GLava with `-bglx` and `"native"` transparency. If the GLX backend works on XWayland, then I will simply change how GLava behaves by default to _always_ use GLX directly over GLFW so `"native"` transparency always works (unless _only_ a wayland compositor is present without XWayland).

**Comment by Toshimonster** [comment]
@wacossusca34 I can confirm it works. The only issue being that it launches on only half the screen ; but the transparancy works without flaw, and the positioning is behind all and in the background.

**Comment by Toshimonster** [comment]
https://imgur.com/a/o1QE6

Tried on both Plasma with wayland and sway.

**Comment by Aaahh** [comment]
The window isn’t half way vertical?
I had this issue with spectrymizer on X11 before i went to glava, I think the desktop flag equivalent caused it.
Dock or any other window type worked I think I remember

**Comment by wacossusca34** [comment]
I really don't see an actual issue here. `"xroot"` not working on XWayland is to be expected -- `"native"` transparency is the default in 1.4.1 anyway and should be used in this case.

**Comment by wacossusca34** [comment]
`-bglx` should be no longer nessecary on XWayland with GLava 1.4.3 and later
