### ISSUE TITLE
Tagged releases

### ISSUE THREAD

**Issue by coderobe** [wacossusca34/glava#25]
Have you thought about tagging "stable" commits once in a while?
This would allow proper distribution packaging from known-good commits.

**Comment by wacossusca34** [comment]
Anything in `master` is stable and (mostly) tested. I use `unstable` for anything currently being tested and then merge it.

Do you mean github releases? Or do you just want commits tagged to distinguish between versions?

**Comment by wacossusca34** [comment]
Releases are now properly tagged.
