### ISSUE TITLE
Left audio buffer is not used

### ISSUE THREAD

**Issue by wacossusca34** [wacossusca34/glava#28]
I'm surprised nobody noticed this! The left audio buffer is not currently being used due to an issue with how `glActiveTexture` is being called, and is currently being filled with the contents of the right buffer instead.

Should be fixed shortly.

**Comment by Aaahh** [comment]
idk if it's an option but could we get a unified setting, (as in this bug fix was not pushed)

**Comment by wacossusca34** [comment]
Sure, make a separate issue for the feature request. My schedule is a bit full right now, so it would be even easier if you just sumbitted a PR.

**Comment by Aaahh** [comment]
Exams, no problem I reverted this on my build anyway

**Comment by wacossusca34** [comment]
Also, since you seem to be following development more closely and making contributions of your own, I suggest getting in touch with me via IRC on freenode (message user `Jarcode`).
