### ISSUE TITLE
"glfw-x11 and glfw-x11-git are in conflict (glfw)"

### ISSUE THREAD

**Issue by Jont828** [wacossusca34/glava#29]
I am running Arch and when I try to update glava through the AUR, I get the following error message. 

`glfw-x11 and glfw-x11-git are in conflict (glfw). Remove glfw-x11-git? [y/N]`

However, if I answer yes to removing glfw-x11-git, I get the following error message:

```error: failed to prepare transaction (could not satisfy dependencies)
:: glava-git: removing glfw-x11-git breaks dependency 'glfw-x11-git'
:: Building glava-git package(s)...
==> Making package: glava-git r133.5ac2cc4-1 (Sun Mar  4 23:30:00 EST 2018)
==> Checking runtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...
:: glfw-x11 and glfw-x11-git are in conflict (glfw). Remove glfw-x11-git? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: glfw-x11 and glfw-x11-git are in conflict
==> ERROR: 'pacman' failed to install missing dependencies.
:: failed to build glava-git package(s)
```

Yaourt gives me this message: 
`:: glava-git: removing glfw-x11-git breaks dependency 'glfw-x11-git'[/code]`

This comes up every time I try to upgrade my packages using pacaur. What should I do? Thanks!

**Comment by wacossusca34** [comment]
If you had read the comments of `glava-git` on the AUR, you would notice a user with a similar issue, where @coderobe gave the reply:

> @Pol_M: Yaourt strikes again. Yaourt can't build split packages correctly, and chokes on the glfw-git pkgbase. This is not an issue with the package - complain to the yaourt developers and use something else.

Also, this has nothing to do with GLava or even the AUR package. Use a different AUR helper.

**Comment by coderobe** [comment]
This is a different issue to the one in the AUR comments - I've recently changed the dependency from glfw-git to glfw-x11 after anthraxx suggested it on the ml; which is problematic because `glfw-x11-git` does not provide `glfw-x11` (which it totally should), but both have a conflict on `glfw`. Depending on `glfw` however is not an option because `glfw-wayland` & co also provide `glfw`. What happens now is that users that have this already installed get a prompt to replace the -git version with the one from the repos, and users with automatic helpers like yaourt come and complain because they don't understand what's happening.

Solution: press yes on the replacement prompt; stop using yaourt

**Comment by coderobe** [comment]
Oh, and if you really need glfw-x11-git for some other reason, modify the glfw-git pkgbuild so that glfw-x11-git and glfw-wayland-git provide glfw-x11 & glfw-wayland respectively. This is an issue with the glfw-git pkgbuild which is not under my control.

**Comment by Jont828** [comment]
Thanks for the response! Sorry if my post wasn't clear, but I was using pacaur first, and then after it didn't work, I tried yaourt as a backup. Should I just manually remove `glfw-x11-git` try the installation again, or should I find another helper besides pacaur and yaourt? Also, someone on the forums suggested that I remove `glava-git` and `glfw-x11-git` and just reinstall `glava-git` after. Would that work? Thanks!

**Comment by coderobe** [comment]
Jeez, no. I have already posted the only correct solution.
You got prompted: `:: glfw-x11 and glfw-x11-git are in conflict (glfw). Remove glfw-x11-git? [y/N]`
The only thing you have to do is answer with `y`...

**Comment by Jont828** [comment]
Hey, sorry, but I'm still a bit confused. When I answer `y` with pacaur, it says removing `glfw-x11-git` breaks the dependency `glfw-x11-git`. Then, it prints the `Remove glfw-x11-git [y/N]` message again, but it doesn't stop and prompt me for a response. Thanks for your help!

```
:: glfw-x11 and glfw-x11-git are in conflict (glfw). Remove glfw-x11-git? [y/N] 
error: failed to prepare transaction (could not satisfy dependencies)
:: glava-git: removing glfw-x11-git breaks dependency 'glfw-x11-git'
:: Building glava-git package(s)...
==> Making package: glava-git r133.5ac2cc4-1 (Mon Mar  5 12:53:10 EST 2018)
==> Checking runtime dependencies...
==> Installing missing dependencies...
resolving dependencies...
looking for conflicting packages...
:: glfw-x11 and glfw-x11-git are in conflict (glfw). Remove glfw-x11-git? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: glfw-x11 and glfw-x11-git are in conflict
==> ERROR: 'pacman' failed to install missing dependencies.
:: failed to build glava-git package(s)
```

**Comment by coderobe** [comment]
That's your AUR helpers fault.

**Comment by coderobe** [comment]
It's a side-effect of it being a build-time dependency, and your AUR helper not building in a clean chroot.

**Comment by coderobe** [comment]
Ideally, you would build packages in chroots and your problem will go away. Alternatively, either: temporarily break the dependencies, rebuild glfw-git with my complaints addressed (re my first response) or uninstall glava glfw and everything depending on it. All of which are less than ideal solutions.

**Comment by Jont828** [comment]
I uninstalled `glava-git`, and when I reinstalled it, I answered `y` to the prompt to remove `glfw-x11-git`, and it installed without any error messages. Thanks for your help and the quick responses!

**Comment by wacossusca34** [comment]
Locking due to the issue being resolved -- further comments and/or related issues should be submitted to the AUR.
