### ISSUE TITLE
always on top with IceWM

### ISSUE THREAD

**Issue by zaza42** [wacossusca34/glava#3]
I can't put the window to a lower layer, and it is always on top regardless of any wm setting even from menu or `winoptions` file or commandline tool `icesh`.
![glava-ontop](https://user-images.githubusercontent.com/16356124/34711004-d1441240-f51d-11e7-9589-e66b904616ec.png)

**Comment by wacossusca34** [comment]
Please post the contents of your `rc.lua`. I have found that using `#request setfocused true` can have this effect on the underlying windowing system. In fact, I think that option should default to `false`.

**Comment by wacossusca34** [comment]
Perhaps that should also default to `false`!
