### ISSUE TITLE
GLXBadFBConfig on 32-bit systems

### ISSUE THREAD

**Issue by EliTheCoder** [wacossusca34/glava#34]
When trying to install GLava, I get this error when I type `make` in the GLava directory. It's probably some stupid mistake I'm making (I'm sort of a newb at Linux). I'm on Ubuntu 16.04 LTS 32 bit.
```
elithecoder@Eli-PC:~/glava$ make
cc -I glad/include -DGLAVA_GLX -DGLAVA_GLFW -O2 -march=native -DGLAVA_UNIX  -o xwin.o -c xwin.c
xwin.c:17:39: fatal error: X11/extensions/Xcomposite.h: No such file or directory
compilation terminated.
Makefile:69: recipe for target 'xwin.o' failed
make: *** [xwin.o] Error 1
elithecoder@Eli-PC:~/glava$ 
```
output of uname -a:
```
Linux Eli-PC 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:26:51 UTC 2018 i686 i686 i686 GNU/Linux
```

**Comment by EliTheCoder** [comment]
Nevermind, all I had to do was reclone the git with --recursive and now it works. Sorry!

**Comment by EliTheCoder** [comment]
I thought I had fixed it by recloning the git with --recursive, but I spoke too soon. I'm still getting the same error

**Comment by wacossusca34** [comment]
Your initial issue was just not having the correct development headers (packages) installed. If you could let me know the name of the package you installed to fix it during compilation, I can add it to the `README.md` file.

Your second issue sounds like a bug. I need the following things to debug the issue:

* The output of `glxinfo | grep OpenGL`
* The name of your window manager
* The name of your X11 compositor (if present)
* The bit depth of your primary screen

It's probably some issue for 32-bit builds of GLava, in which case I encourage you to make a debug build and run GLava through gcc (`make BUILD=debug INSTALL=standalone` and then `gcc ./glava`). I can also try debugging the issue myself when I have time.

**Comment by EliTheCoder** [comment]
To fix my initial problem, I installed the `libxcomposite-dev` package through `apt-get`.
***
Here's my system information:
Output of `glxinfo | grep OpenGL`:
```
OpenGL vendor string: Intel Open Source Technology Center
OpenGL renderer string: Mesa DRI Intel(R) G41 x86/MMX/SSE2
OpenGL version string: 2.1 Mesa 17.2.8
OpenGL shading language version string: 1.20
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 17.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:
```

Output of `screenfetch`:
![](https://i.imgur.com/QZgpBF7.png)

Bit depth of primary (only) screen: 24
***
Thanks for the help :)

**Comment by wacossusca34** [comment]
I'm not sure why I need to point this out, but this:

```
OpenGL version string: 2.1 Mesa 17.2.8
[...]
OpenGL shading language version string: 1.20
[...]
CPU: Pentium Dual-Core CPU E5300 @ 2.603GHz
GPU: Mesa DRI Intel(R) G41 x86/MMX/SSE2
```
is quite old hardware. Even if OpenGL 3.3 was supported by your driver (it isn't), GLava would eat up resources you would probably otherwise like to have free for other tasks with that kind of specs.

There's nothing wrong with using old hardware like this, but don't expect applications using modern OpenGL to work. Backporting to OpenGL 2.1 is not of interest to me since most people will use a dedicated GPU with such hardware nowadays.
