### ISSUE TITLE
Unable to compile on Mint

### ISSUE THREAD

**Issue by TheRoyalLion** [wacossusca34/glava#38]
First of  all I'm pretty new to git hub and compiling myself, but under Mint I don’t seem to find den Package libglx0, the only package that looks remotely like this is libxcb-glx0. I just resumed with the compilation and got that error : 
cc -o glava glava.o xwin.o pulse_input.o glsl_ext.o glfw_wcb.o glx_wcb.o fifo.o render.o glad.o  -lpulse -lpulse-simple -pthread -lglfw -ldl -lm -lX11 -lXext -lGLX -lXrender
/usr/bin/ld: cannot find -lGLX
collect2: error: ld returned 1 exit status
Makefile:77: recipe for target 'glava' failed

**Comment by RedKugelblitz** [comment]
libglx is implemented by graphics drivers afaik. apt-get the glx related packages for your gpu

**Comment by wacossusca34** [comment]
This seems to be a reoccuring issue on some systems where the graphics driver does not provide a `libGLX.so` (other users have reported required symbols are resolved from `libGL.so`). See issue #22 as submitted by @Aaahh for more information.

If you don't have an Nvidia PRIME or Bumblebee installation, you probably just need the relevant GLX package for your driver.

**Comment by wacossusca34** [comment]
Closing since @TheRoyalLion has not indicated the issue persists.

**Comment by TheRoyalLion** [comment]
Sorry forgot about it but #22 helped a lot and it works now perfectly fine.
