### ISSUE TITLE
GLX functions do not load correctly on Bumblebee and Nvidia PRIME systems

### ISSUE THREAD

**Issue by wacossusca34** [wacossusca34/glava#41]
Currently GLava just loads GLX functions (and extensions) by hand, uses `-lGLX` in the makefile to link to the implementation and provided GLX headers. This does wonky things when there's more than one available driver, and I'm not sure what the "proper" behaviour is here. Apparently, changing the linker option in the `Makefile` to `-lGL` fixes the issue, but I'm not sure if this is ideal (what driver is it using, does it respect `optirun` or `DRI_PRIME=1`?)

I attempted to load GLX functions through glad, since that's an option (see `gladLoadGLX(display, screen)`), but it appears the GLX loader for glad doesn't seem to work correctly. The `glad2` branch contains fixes for the GLX generators, but it's very unstable (can't even get it to run).

See: https://github.com/Dav1dde/glad/issues/107, https://github.com/Dav1dde/glad/issues/23

I'm probably going to implement my own solution using `dlopen`, once I figure out what I'm supposed to do on systems with hybrid graphics. See #22 for the original issue submitted by @Aaahh.

**Comment by wacossusca34** [comment]
@Aaahh should be fixed, now. GLava doesn't need `-lGL` or `-GLX` anymore and just uses `dlopen` and `dlsym` to find the functions it needs from OpenGL libraries. It turns out on my system simply using `-lGL` also works (it exports GLX symbols), but since I'm not sure this is the case with all drivers (non GLVND/legacy nvidia drivers?) I will check both libraries. See:

```C
    void* resolve_f(const char* symbol) {
        void* s = NULL;
        if (hgl)        s = dlsym(hgl,  symbol);
        if (!s && hglx) s = dlsym(hglx, symbol);
        if (!s) {
            fprintf(stderr, "Failed to resolve GLX symbol: `%s`\n", symbol);
            exit(EXIT_FAILURE);
        }
        return s;
    }
```

**Comment by Aaahh** [comment]
Gucci
