### ISSUE TITLE
Issue launching in elementary OS 0.4.1 loki

### ISSUE THREAD

**Issue by Preston-PLB** [wacossusca34/glava#42]
I followed the instructions to a T in the README.MD. Installed all the dependencies and ran `glava --copy-defualt`. When I run `glava -v` I get

```
Using backend: 'glx'
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
glXChooseFBConfig(): failed
Aborted (core dumped)

```
Here is my rc.glsl with removed comments

```
#request mod bars

/* Window hints */
#request setfloating  false
#request setdecorated true
#request setfocused   false
#request setmaximized false

#request setforcegeometry false

#request setopacity "native"

#request setversion 3 3
#request setshaderversion 330

#request settitle "GLava"

#request setgeometry 0 0 800 600

#request setbg 00000000
#request setxwintype "normal"

// #request addxwinstate "sticky"
// #request addxwinstate "skip_taskbar"
// #request addxwinstate "skip_pager"
// #request addxwinstate "above"

#request setsource "auto"

#request setswap 1

#request setinterpolate true

#request setframerate 0

#request setprintframes true

#request setsamplesize 1024

#request setbufsize 4096

#request setsamplerate 22050

#request setbufscale 1
```

Here is my screen fetch for reference 

```
                                     preston@PAtches
         eeeeeeeeeeeeeeeee           OS: elementary OS 0.4.1 loki
      eeeeeeeeeeeeeeeeeeeeeee        Kernel: x86_64 Linux 4.13.0-38-generic
    eeeee  eeeeeeeeeeee   eeeee      Uptime: 1h 21m
  eeee   eeeee       eee     eeee    Packages: 2043
 eeee   eeee          eee     eeee   Shell: bash 4.3.48
eee    eee            eee       eee  Resolution: 1920x1080
eee   eee            eee        eee  WM: Mutter(Gala)
ee    eee           eeee       eeee  WM Theme: elementary
ee    eee         eeeee      eeeeee  CPU: AMD Athlon X4 860K Quad Core @ 3.7GHz
ee    eee       eeeee      eeeee ee  GPU: GeForce GTX 1050 Ti
eee   eeee   eeeeee      eeeee  eee  RAM: 1731MiB / 10001MiB
eee    eeeeeeeeee     eeeeee    eee 
 eeeeeeeeeeeeeeeeeeeeeeee    eeeee  
  eeeeeeee eeeeeeeeeeee      eeee   
    eeeee                 eeeee     
      eeeeeee         eeeeeee       
         eeeeeeeeeeeeeeeee          

```

What am I doing wrong? Do I need to do something extra in the configs I don't know about? Do I need to change WM? 

Thank you for your help!

**Comment by Aaahh** [comment]
run `LIBGL_DEBUG=verbose glxgears` and post output
run `ls -l /usr/lib64/dri/*swrast*` too
try `sudo apt-get install mesa-utils`
I think it's your Nvidia drivers, we can either debug it, or you can reinstall all your nvidia drivers

**Comment by wacossusca34** [comment]
@Aaahh is correct, this sounds like a driver related issue, although it could be related to #41. GLava first tries to load from `libGL.so`, and then `libGLX.so` for GLX symbols. Your `libGL` should not be trying to load `swrast` if you are using the `nvidia` driver.

Generally this is caused by library conflicts with Mesa and `nvidia`'s OpenGL libraries where `libglvnd` is _not_ being used.

@Preston-PLB In additions to @Aaahh's requests, please post the output of `glxinfo | grep OpenGL` and how you installed your graphics drivers (official package, external PPA, or Nvidia's proprietary installer).

**Comment by Preston-PLB** [comment]
@Aaahh 
`LIBGL_DEBUG=verbose glxgears`

```
Running synchronized to the vertical refresh.  The framerate should be
approximately the same as the monitor refresh rate.
301 frames in 5.0 seconds = 60.011 FPS
301 frames in 5.0 seconds = 60.000 FPS
301 frames in 5.0 seconds = 60.000 FPS
301 frames in 5.0 seconds = 60.002 FPS
301 frames in 5.0 seconds = 59.999 FPS
301 frames in 5.0 seconds = 60.001 FPS
300 frames in 5.0 seconds = 59.999 FPS
300 frames in 5.0 seconds = 59.993 FPS
301 frames in 5.0 seconds = 60.002 FPS
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 50 requests (50 known processed) with 0 events remaining.
```
`ls -l /usr/lib64/dri/*swrast*`

```
ls: cannot access '/usr/lib64/dri/*swrast*': No such file or directory
```

@wacossusca34 

I use the official ubuntu repository to get my drivers. But have the nvidea 390 driver run file if I need to use that.

`glxinfo | grep OpenGL`

```
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1050 Ti/PCIe/SSE2
OpenGL core profile version string: 4.5.0 NVIDIA 384.111
OpenGL core profile shading language version string: 4.50 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5.0 NVIDIA 384.111
OpenGL shading language version string: 4.50 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 384.111
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

```

**Comment by wacossusca34** [comment]
@Preston-PLB 
> I use the official ubuntu repository to get my drivers.

It appears the majority of the people encountering this type of issue on general are using ubuntu repositories. I'm putting my money on this being a package conflict, playing around with `libGL.so.1` symlinks seems to be the accepted solution (... which isn't really acceptable for a widely used distro).

Two things to try:

* Play around with library symlinks for `/usr/lib/libGL.so` and query your package manager to figure out where it's provided from.

* Try the `v1.4.4` tag of GLava from the `master` branch. This predates a fix that makes GLava dynamically load GLX functions and instead just links to `libGLX.so`, which might fix the problem for you. Some systems (including my own) provide working GLX symbols through `libGL` _or_ `libGLX`, but hybrid graphics systems sometimes lack the latter.

> But have the nvidea 390 driver run file if I need to use that.

Don't. Nvidia's installer is famous for causing problems after installation.

**Comment by Aaahh** [comment]
Ubuntu switched how the package nvidia drivers and nvidia dropped support and changed things with 390, so Ubuntu seems to be still accommodating

**Comment by Preston-PLB** [comment]
I changed the symlinks in `usr/lib` of `libGL.so`, `libGL.so.1`, and `libGLX.so`. They are all linked to their respective files in `usr/lib/nvidea-384` however, I still get the same error.

I went to v1.4.4 and only got less error message.
```
Using backend: 'glx'
Segmentation fault (core dumped)
```

**Comment by Preston-PLB** [comment]
Update: `sudo apt-get purge nvidia*` fixed my issue.

I got mad and decided to just nuke the drivers and all seems to be well. If I wanted to game or 3d render this isn't ideal as now I am using the mesa drivers. However I have windows for that, I mainly use linux for my school work. 

Thank you @Aaahh and @wacossusca34 for your help even though this problem wasn't caused by your software. Keep up the great work!!

**Comment by wacossusca34** [comment]
@Preston-PLB If other OpenGL applications were working correctly prior to removing the `nvidia` driver, I am still interested to see why the issue was occurring. The segmentation fault when you tried `v1.4.4` would be nice to get a backtrace on.

**Comment by Aaahh** [comment]
I think it's just an incomplete nvidia driver, when I run `glxinfo | grep OpenGL` I get
```
OpenGL core profile version string: 4.6.0 NVIDIA 390.48
OpenGL version string: 4.6.0 NVIDIA 390.48
OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 390.48
```
Ubuntu renamed the driver package to something and then renamed it again to nvidia-390, so it might have thrown stuff off. Also, you need the new xorg which I think is only on proposed 18.04 right now
