### ISSUE TITLE
Compiling on nixOS

### ISSUE THREAD

**Issue by eadwu** [wacossusca34/glava#46]
When compiling the errors of `error: unknown type name` always pop up which I don't even know what it means. Some googling leads to `https://www.reddit.com/r/opengl/comments/5xbbqm/please_help_with_glad/` which talks about the `include_directories` order.

Output 
With `BUILD=debug`
https://pastebin.com/5tD8vPPg

Without `BUILD=debug`
https://pastebin.com/Se6jmYSJ

**Comment by eadwu** [comment]
Nevermind, got it to successfully compile on `master`, however the latest release (v1.4.5) doesn't compile successfully.

**Comment by wacossusca34** [comment]
The `glad` submodule needs to be updated manually if you are using an older release. Apparently something changed with the source(s) that glad uses to generate headers and it needed to be updated for that.
