### ISSUE TITLE
Combining Left and Right audio

### ISSUE THREAD

**Issue by diogotr7** [wacossusca34/glava#53]
Either combining them or let the user choose one. I currently have mine setup so the "bars" view is 3840 pixels wide and spans 2 monitors (one to the left of mine) to get just the right channel on my monitor. I feel it's not ideal and a combination of both channels could be used to show one side at a time.

I'm sorry if i worded this weirdly.

**Comment by wacossusca34** [comment]
@diogotr7 implemented in `master`. Shouldn't break anything unrelated, and works in my (minimal) testing.
