### ISSUE TITLE
Compilation terminated on Ubuntu 18.04.1

### ISSUE THREAD

**Issue by swingcake** [wacossusca34/glava#55]
When I,
```
$ make
..
xwin.c:19:10: fatal error: X11/extensions/Xcomposite.h: No such file or directory
 #include <X11/extensions/Xcomposite.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:74: recipe for target 'xwin.o' failed
make: *** [xwin.o] Error 1
```

**Comment by wacossusca34** [comment]
`sudo apt-get install libxext-dev` will solve the issue. `libXext` is one of the build requirements, which on ubuntu, include the `-dev` packages since they contain the headers.

**Comment by swingcake** [comment]
Actually I do have that package installed. I did run
`sudo apt install libpulse0 libpulse-dev libglfw3 libglfw3-dev libxext6 libxext-dev python make gcc` before
`$ make`

![screenshot from 2018-08-12 10-37-29](https://user-images.githubusercontent.com/32037820/43998800-0f48b03a-9e1c-11e8-9778-9ad8d4f2e3a4.png)

**Comment by wacossusca34** [comment]
Oh, the composite extension headers are actually in `libxcomposite-dev`. Sorry about that, I will update the readme.

That being said, a simple good search for the missing header would have revealed what package you needed!
