### ISSUE TITLE
Running glava corrupts terminal emulator contents

### ISSUE THREAD

**Issue by LeOtaku** [wacossusca34/glava#57]
I do not know if this is a problem you can influence/fix in any way, but here it is:

Whenever I run glava, the output from my urxvt (rxvt_unicode) terminals gets mangled extremely badly. This only happens when the visualizer is running and immediately stops when I close it.

Any help is appreciated, thank you for your hard work!

**Comment by wacossusca34** [comment]
This is the most absurd and hilarious bug I've personally come across. I highly doubt my code is causing this (may be an X11, compositor, or X11 graphics driver bug), but I'm curious enough to leave this open. Could you provide a screen recording of the issue?

**Comment by LeOtaku** [comment]
Thank you for looking into my problem. As I've said, I myself did not think this was "your fault" (I will look into X11 compositor/drivers today). 

Anyways, here is the video:
https://streamable.com/8bpsp

**Comment by Aaahh** [comment]
Nice setup, I would love the details on that. (WM?)

As for the terminal, I’ve ran into that before, usually when my system is hitting bricks. 
Maybe it’s related to the terminal emulator, try running glava from tty or some other way and see if you still run into that. I think it’s just your luck that glava is making this bug more expressive.

**Comment by LeOtaku** [comment]
I indeed have been able to fix this problem by tweaking my compton (compositor) configuration. So this can likely be closed as "not a bug". Sorry.

@Aaahh: My WM is fvwm based on @addy-dclxvi's configuration. If you want any more information, you could open an issue at my dotfiles repo. I/We should probably not clutter this issue board any further.

**Comment by wacossusca34** [comment]
> I indeed have been able to fix this problem by tweaking my compton (compositor) configuration. So this can likely be closed as "not a bug".

@LeOtaku what setting in compton was causing it in the first place? This looks like something you can report there.

> Sorry.

No worries.

**Comment by wacossusca34** [comment]
Oh, and if you could confirm that using GLava with fvwm has no other issues or configuration bits, I can go ahead and update the readme.

**Comment by wacossusca34** [comment]
> [...] the compton wiki explicitly states that some options are only intended to be used with certain hardware/drivers and manual testing is required.

@LeOtaku looks like that is this case here:

> * `--glx-use-copysubbuffermesa` is effective when only a small part of your screen is updated. The drawback is it generally works only with Mesa drivers, and LLVMpipe may have some issues handling it. It may or may not have a negative effect on `--vsync opengl-swc/opengl-mswc`.

If you _are_ on mesa graphics then you should report this to compton.

> About Fvwm, setting #request setxwintype "desktop" in rc.glsl seems to just work. The only other thing I had to do is to put *FvwmPager: UseSkipList in my fvwm config. This of course is relevant only to users of FvwmPager and also not specific to GLava.

That is plenty helpful.
