### ISSUE TITLE
Transparent Ui

### ISSUE THREAD

**Issue by LinArcX** [wacossusca34/glava#62]
Hi. i have arch linux and install glava from Aur.
when i want to run it:
[error](https://raw.githubusercontent.com/LinArcX/Ganje/master/Images/LinArcx/Screenshot%20from%202018-09-24%2021-02-44.png)
Desktop environment: Gnome 3.30

**Comment by wacossusca34** [comment]
@LinArcX A few notes:

* Compile `master` from git and reports errors from that.

* The default `bars` module will display nothing if no sound is playing, which is _intentional_.

* GLava does not have any other UI, it is configured via shader sources and directives.

It seems like you have not read the [documentation](https://github.com/wacossusca34/glava/blob/master/README.md). If you need clarification on something in particular, you are free to ask.

**Comment by LinArcX** [comment]
Thank you for reply.
I clone the repository, compile it from source(master branch) and follow instructions. but nothing change!

**Comment by coderobe** [comment]
Nothing will change unless you configure GLava to do something different.

**Comment by Aaahh** [comment]
Leave it open and try playing audio, if that doesn’t work then check pulse audio control panel

**Comment by LinArcX** [comment]
@coderobe How?!

**Comment by wacossusca34** [comment]
@LinArcX Please go read the documentation. Locking.
