### ISSUE TITLE
Additional options for bars configuration

### ISSUE THREAD

**Issue by RaitaroH** [wacossusca34/glava#64]
First of all I would love to be able to put Glava on the right edge of my screen. Is it even possible through a custom bars config or not?

Also if that happens, I wold like the bars to go from the left edge to the right. So basically is like flipping the whole thing.

I tried `#define ROTATE ()` in the bars.glsl but with not much success. If anything it only moves the window around the screen if I don't set Glava to my window screen.

**Comment by wacossusca34** [comment]
@RaitaroH If I understand your requirements, you can't configure such in the `bars.glsl` file, but the shaders for the module can certainly be edited to allow that. I can add more options for the `bars` module if I find the time.

Just to clarify, you want:

* Vertically rendered or 90 degree rotated `bars` module (not possible without editing shaders)
* Inverted audio buffers (currently possible, use `#define DIRECTION 1`).

Is that correct?

**Comment by RaitaroH** [comment]
To get that I had to rotate in GIMP by `-90`. 
![clear](https://user-images.githubusercontent.com/19552720/46390220-75227800-c6df-11e8-9218-4695c56c4bde.png)

Also I don't think `#define DIRECTION 1` is that. To me it looks like it flips the bars horizontally and adds a divider in the middle. In case you would like to put this on the top (which I don't but hey) the flip would be nice. Here is what I mean:
![flip](https://user-images.githubusercontent.com/19552720/46390318-ef52fc80-c6df-11e8-970c-6baeef1f439e.png)

**Comment by wacossusca34** [comment]
@RaitaroH and that commit added `#define MIRROR_YX 1`, which effectively switches the X and Y axis in the shader, causing it to render on the left side of the window. You can use `#define FLIP 1` in combination with this option to make it render on the right.

**Comment by RaitaroH** [comment]
@wacossusca34 awesome. Thank you.

**Comment by RaitaroH** [comment]
![screenshot_20181004_075159](https://user-images.githubusercontent.com/19552720/46453472-60f77d00-c7aa-11e8-9f3f-c439e2a353be.png)

Result.

**Comment by allusive-dev** [comment]
Hello, I saw this and had a similar feature request. Can you make bars able to have a custom rotation set like you can with radial. I am wanting the bars on a specific angle but after fiddling with the frag files I am not sure how to get it to work?
