### ISSUE TITLE
Above fullscreen

### ISSUE THREAD

**Issue by RaitaroH** [wacossusca34/glava#65]
Watching video,
But glava will stay below...
It should be above.

**Comment by RaitaroH** [comment]
Just to be clear: if I watch a video in fullscreen in browser or media player, it would be nice if glava wold be able to stay above those as well.

**Comment by wacossusca34** [comment]
`#request addxwinstate "above"` will accomplish this, but it means it will be above all windows, not just when a window is fullscreen. You should still be able to click through it if it's a desktop window, otherwise make sure `#request setclickthrough true` is set.

**Comment by RaitaroH** [comment]
> `#request addxwinstate "above"` will accomplish this, but it means it will be above all windows, not just when a window is fullscreen. You should still be able to click through it if it's a desktop window, otherwise make sure `#request setclickthrough true` is set.

I did that before opening the issue, both in rc and kwin files. "below" is quoted too. Glava just doens't stay above fullscreens, nor does anything else that is "above". I just thought "above" was for above windows that are not fullscreen or something like that. Even if I set the above with kwin, wmctrl or in this case the config file. This is how it is in KDE Neon 5.13.5 (ubuntu 18.04).

**Comment by wacossusca34** [comment]
@RaitaroH I'll spin up my KDE container later today and try to find something that works. It is really frustrating that the WM routinely misbehaves with EWMH wints and window types, perhaps a collection of these problems I have had with GLava should make their way into a KWin issue.

**Comment by wacossusca34** [comment]
Closing due to technical reasons making this impossible to implement elegantly, see [my related comment in another issue](https://github.com/wacossusca34/glava/issues/4#issuecomment-427216315).

**Comment by wacossusca34** [comment]
It was occurred to me that `override_redirect` may allow me to map GLava's window without the window manager even knowing, so there's still a chance that I could get this issue fixed.

**Comment by RaitaroH** [comment]
@wacossusca34 The windows stays above fullscreen... but it freezes. So is basically an unfocused overlay now instead of actually visualizing anything. I tried `!` `!+` `!-` with force raised and not, both in kwin and rc files and I couldn't get this to work. I am on nviida prop drivers, perhaps that could have something to do with it.

**Comment by wacossusca34** [comment]
@RaitaroH oh, I forgot to mention that you will also need to set `#request setfullscreencheck false`. This is supposed to prevent GLava from eating resources that fullscreen applications would normally use by halting the rendering, but in your case you will want it disabled.

**Comment by RaitaroH** [comment]
@wacossusca34 I added that too... still freezes.

Also, I do remember glava working without options... but now I get a crash.
```
▶ glava
Using backend: 'glx'
[1]    9574 segmentation fault  glava
▶ glava -d                    
Using backend: 'glx'
Loading module: 'bars'
found GLSL stage: '1.frag'
compiling: '1.frag'
Using default PulseAudio sink: compressor-stereo.monitor
```

**Comment by wacossusca34** [comment]
@RaitaroH crashes need to be debugged with `make BUILD=debug` and `gdb glava`. Posting your `rc.glsl` (and any other changed files) will help.

**Comment by RaitaroH** [comment]
Ok so...
```
▶ glava --verbose
Using backend: 'glx'
Assigning debug callback
[1]    16688 segmentation fault  glava --verbose

 SEGV(-11)
```
Works with `-d`
```
▶ glava -d -v              
Using backend: 'glx'
Assigning debug callback
Loading module: 'bars'
found GLSL stage: '1.frag'
compiling: '1.frag'
Using default PulseAudio sink: compressor-stereo.monitor
```

I did also build with debug but, glava crashes on start:
```
▶ gdb glava      
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from glava...done.
(gdb)
```

Here is my configs right now:
[bars.txt](https://github.com/wacossusca34/glava/files/2449971/bars.txt)
[env_KWin.txt](https://github.com/wacossusca34/glava/files/2449972/env_KWin.txt)
[rc.txt](https://github.com/wacossusca34/glava/files/2449975/rc.txt)

**Comment by RaitaroH** [comment]
Also `#request setforceraised true` did the trick for `GLava (glava) v1.5.1-11-g353c3bd (stable, unix/fhs)`

Thank you. Now I have in my kwin file:
```
#request setdecorated false
// #request setxwintype "normal"
#request setxwintype "!"
#request addxwinstate "undecorated"
#request addxwinstate "above"
// #request addxwinstate "below"
#request addxwinstate "skip_taskbar"
#request addxwinstate "skip_pager"
#request addxwinstate "pinned"
#request addxwinstate "sticky"
#request setclickthrough true
#request setforceraised true
#request setfullscreencheck false
#request setforceraised true
```

**Comment by coderobe** [comment]
Your GDB output is the default gdb startup banner, you have not yet started the program inside the debugger

**Comment by RaitaroH** [comment]
@coderobe ups. I fixed it.

**Comment by kirolos-mater** [comment]
> Watching video,
> But glava will stay below...
> It should be above.

Don't use "glava --desktop" command, only "glava" & #request setxwintype "dock"
