### ISSUE TITLE
Use VisibilityNotify X11 events instead of checking for _NET_WM_STATE_FULLSCREEN

### ISSUE THREAD

**Issue by KomaGR** [wacossusca34/glava#68]
As stated, the visualiser ceases to update its animation the moment full-screen window is focused. My most prominent examples are Netflix and YouTube on full-screen. 

When the full-screen video is focused the visualiser locks in place. When it is unfocused it picks up the stream anew.

Is this behaviour intended?

**Comment by wacossusca34** [comment]
As it says in `rc.glsl`:

> ```GLSL
> /* Enable/disable fullscreen checks. This looks at the currently
>    focused window and halts GLava's rendering if it is
>    fullscreen. This prevents rendering from interfering with
>    other graphically intensive tasks. */
>#request setfullscreencheck true```

It's intended and configurable. You can also use `#request setxwintype "!+"` in some WMs if you want to display GLava over fullscreen windows (see #65), although I'm guessing you just had it running on another monitor.

It may be more elegant to use `VisibilityNotify` events (if the `state` member is set to `VisibilityFullyObscured`), that way users don't need to muck with this option.

**Comment by wacossusca34** [comment]
@KomaGR GLava (`master`) is now smarter about detecting when it is visible; minimized and obscured windows will suspend rendering, and the fullscreen check is disabled by default now (as it's mostly made obsolete by this change, although some users may want it enabled on multi-monitor setups).
