### ISSUE TITLE
Plasma/KDE - glava seems to flip

### ISSUE THREAD

**Issue by Patiga** [wacossusca34/glava#69]
Since I am a newbie to both linux and glava, this might just be due to a mistake in my configurations.
However, I use the radial module with the 'utility' window mode (I also tested most of the other modes).
Since glava is supposed to match my wallpaper, I want it to be in a specific spot. It usually is, but if some event occurs (I have no idea what causes it), the glava window seems to flip (the border of the glava window is no longer is on the top, but the bottom), misplacing it. If it happens once, I am not able to get it to work again until i restart.
Further Note: every time i open glava with a bash-script, it seems to be in this weird flipped state.

*Edit: It seems like it didn't suddenly flip, but fix the former flip. o.O
(thought it was the other way around)

Further question: Is there some way to extend the window to my screen size and move the bars/circle/...?

**Comment by wacossusca34** [comment]
@Patiga unfortunately this is a KDE issue. It likes to save window positions and sets them upon application window mapping. A temporary fix is provided via `#request setforcegeometry true`.

**Comment by Patiga** [comment]
> @Patiga unfortunately this is a KDE issue. It likes to save window positions and sets them upon application window mapping. A temporary fix is provided via `#request setforcegeometry true`.

Nice, that works nicely!
i'm still curious whether its possible to use glava in fullscreen and move the circle.
(so the bars are not cut off)

**Comment by wacossusca34** [comment]
@Patiga if your bars are "cut off", it's probably because the window you have specified isn't large enough for your shader options. Just make the window geometry larger with `#request setgeometry ...`.

If you want to use GLava while another window is fullscreen, you will need to use [unmanaged windows](https://github.com/wacossusca34/glava/issues/65#issuecomment-427235094) by using `#request setxwintype "!+"`.

If you want GLava _itself_ to be fullscreen, I don't have a formal (EWMH) option for that, but you can 'force' it to be fullscreen using the aformentioned `"!+"` window type, just covering the entire screen instead.

If you want GLava to be treated as a regular window and occasionally have it fullscreen, then you should have your window manager handle that. KWin (KDE) has global shortcut option for this, although it is not bound to a key by default, see [this answer](https://askubuntu.com/a/522891) if you want to do so.

**Comment by Patiga** [comment]
@wacossusca34 doesn't `#request setgeometry` declare the window size and would thereby move the visualization?

**Comment by wacossusca34** [comment]
@Patiga yes. The `circle` module is centered on the window, so if you want to increase the area it has to render, while keeping it in the same place, then subtract half the added width and height from the x and y positions respectively.

**Comment by Patiga** [comment]
@wacossusca34 that explains a lot. Am I correctly assuming the task-bar can not belong to a window of a non-desktop window-modes?

Also quick note: in the radial module, there is a gap on one of the sides where the left/right audio input meet. It gets easier noticeable the more & thinner bars you use.

**Comment by wacossusca34** [comment]
@Patiga I'm not completely sure how KDE's taskbar works, but it's probably a dock window. I'm not sure what you mean by "can not belong to a window of a non-desktop window-modes".

> in the radial module, there is a gap on one of the sides where the left/right audio input meet. It gets easier noticeable the more & thinner bars you use

I just fixed this now in the referenced commit.

**Comment by Patiga** [comment]
@wacossusca34 I was trying to ask, whether a utility window (or just any non-desktop mode) can fill the entire screen extending above the task-bar.

Also, it would be a great feature to be able to move the visualization independent of the window!

**Comment by wacossusca34** [comment]
> whether a utility window (or just any non-desktop mode) can fill the entire screen extending above the task-bar.

You probably want a normal window type and a fullscreen hotkey, although this depends on what you mean by "fill the entire screen". X11 and interaction with window managers is unfortunately complex. You can:

* Request the window to be positioned in a way that covers the entire screen. Completely WM-dependent on what the results are with different window types; often with utility windows, they are restricted to the net work area.

* Request the window to be fullscreen (`_NET_WM_STATE_FULLSCREEN`, provided `_NET_WM_ACTION_FULLSCREEN ` is set). WM dependent with different window types.

* Unmanage the window (`CWOverrideRedirect` mask and `override_redirect` attribute set), raise the window above everything else with `XRaiseWindow`, position the window over the entire screen with `XMoveResizeWindow`, and re-parent to the root window (if necessary). This is a hack provided in GLava via _unmanaged windows_ (`"!+"`) and usually just works.

KWin is particularly strange when it comes to certain window types, particularly the `"desktop"` window type, as it fights with the stacking order of KDesktop. KWin also has some extended behavior when it comes to enforcing window hints that can be set via non-standard protocols or via the settings panel for KWin (and can probably be bound to global hotkeys as well).

It's worth noting that GLava's `--desktop` flag doesn't even use desktop window types on KDE (see [`env_kwin.glsl`](https://github.com/wacossusca34/glava/blob/master/shaders/env_KWin.glsl)). It uses a normal window with some hints that make it behave like a desktop window, while properly belonging to the client list. With this flag, you can make GLava fullscreen with `_NET_WM_STATE_FULLSCREEN`. As I mentioned above, you can use [this answer](https://askubuntu.com/a/522891) to configure a key for that.

**Comment by Patiga** [comment]
@wacossusca34 Great! Thanks to the modes "toolbar" and "dock", i got everything to work.
Could you do a quick example on how to make use the non-centered radial module?

**Comment by wacossusca34** [comment]
@Patiga radial is always centered in the GLava window. If you don't want it in the center of your screen, don't use a fullscreen window.

Unless there is a reason why one would want GLava fullscreen, but the selected module only rendering in a portion of it, simply position it with `#request setgeometry x y w h`.

**Comment by Patiga** [comment]
@wacossusca34 The thing is I want GLava to combine well with my wallpaper, while not overlapping the task bar. So i basically want the visualization to be in the middle of the screen, but not overlapping the task bar. To solve this, it would be great, if I was either able to 

1. use fullscreen and tell it to not render in the task bar area

or

2. exclude the taskbar using the window size and push the visualization a bit down to match the wallpaper.

(This is sort of a feature request)

**Comment by coderobe** [comment]
It seems like setgeometry would do the job, like @wacossusca34 mentioned.
Subtract the taskbar height from glava's height twice, and offset y by one taskbar height - ta-da, centered

**Comment by Aaahh** [comment]
I just remembered that you can fix the issue by replacing the root window with glava, but you lose widgets and the wallpaper 
But that gave consist results with kde

**Comment by Patiga** [comment]
@coderobe You are right, it would then align well with the wallpaper. However, then the visualization is being cut off not only at the taskbar, but just as much on the top, and i would love to avoid that.

**Comment by Aaahh** [comment]
Then subtract height only once, unless you mean that you want to crop the window instead of resizing it

Try playing with the numbers to see how it works

**Comment by Patiga** [comment]
@Aaahh To clear things up: The position of the visualization should be in the middle of the screen. I want GLava to extend to the top of the screen, but not to the bottom.

Regarding the variables, to my knowledge x and y define the top left corner of the window and height/width set the size of the window. 

Since the radial module uses the center of the window, for the visualization to be in the middle of the screen the window has to extend the same equally up and down. If that is correct, I don't think I can achieve that setup.

**Comment by Aaahh** [comment]
You’ll have to edit the mod, set the window to full screen and edit the radial module to not extend that far in that lower area. Are you using the new or the old radial module? (Is it bars or a line?) 
You’ll want to mess with Amplify variable, if I have time tomorrow I’ll look at it for u

**Comment by Patiga** [comment]
shouldn't it be possible to edit the lines:
dx = gl_FragCoord.x - (screen.x / 2),
dy = gl_FragCoord.y - (screen.y / 2);
to relocate it?

**Comment by Aaahh** [comment]
Lmao that works too I guess, but that’ll just move the circle, so you’ll want to reposition so Glava covers the top but not the task bar, and then reposition the circle. The disadvantage is it might cause the line/bars to be cut off by the task bar

**Comment by coderobe** [comment]
Can you try https://github.com/wacossusca34/glava/tree/radial-offsets ? I have made a config setting available for this in the main radial.glsl

**Comment by Patiga** [comment]
hmm, since i'm sort of new to git and stuff, could i try to do a commit?
would that be a feature, which could make it to the main branch?

> The disadvantage is it might cause the line/bars to be cut off by the task 
That's what i wanted :(

**Comment by Patiga** [comment]
@coderobe Huh, that's perfect. Going to try to mess with that.

**Comment by coderobe** [comment]
Please report back whether that works for you and i'll merge it to master

**Comment by Patiga** [comment]
@coderobe It works just as intended! Thank you very much @wacossusca34 @coderobe @Aaahh 

Great job btw, the visualizations look fantastic.

But wouldn't merging the branch to the main mess with everyone's config files? Maybe 0 as a default value for the offsets could be added in the radial module.

**Comment by coderobe** [comment]
i don't see how it would. The new shaders only apply when they're copied over and a fresh config has an offset of 0
