### ISSUE TITLE
Trouble compiling

### ISSUE THREAD

**Issue by TechieAndroid** [wacossusca34/glava#7]
`root@austin-System-Product-Name:~/glava# make
cd glad && python -m glad --generator=c --extensions=GL_EXT_framebuffer_multisample,GL_EXT_texture_filter_anisotropic --out-path=.
[01/16/2018 13:30:19][INFO	][glad   	]: getting 'gl' specification from SVN
[01/16/2018 13:30:19][INFO	][glad.opener	]: opening: 'https://raw.githubusercontent.com/KhronosGroup/OpenGL-Registry/master/xml/gl.xml'
[01/16/2018 13:30:19][INFO	][glad   	]: generating 'gl' bindings
[01/16/2018 13:30:20][INFO	][glad   	]: generating 'gl' bindings - done
cc -I glad/include -O2 -march=native -DGLAVA_UNIX  -o glad.o ./glad/src/glad.c -c
cc -I glad/include -O2 -march=native -DGLAVA_UNIX  -o glava.o -c glava.c
cc -I glad/include -O2 -march=native -DGLAVA_UNIX  -o xwin.o -c xwin.c
In file included from xwin.c:21:0:
/usr/include/GLFW/glfw3native.h:102:3: error: #error "No context API selected"
  #error "No context API selected"
   ^
Makefile:58: recipe for target 'xwin.o' failed
make: *** [xwin.o] Error 1`

**Comment by wacossusca34** [comment]
Your version of GLFW3 is out of date. I took the liberty of digging through possible causes despite your lack of information and found the contents of `glfw3native.h` should be:

```C
 #if defined(GLFW_EXPOSE_NATIVE_WGL)
  /* WGL is declared by windows.h */
 #endif
 #if defined(GLFW_EXPOSE_NATIVE_NSGL)
  /* NSGL is declared by Cocoa.h */
 #endif
 #if defined(GLFW_EXPOSE_NATIVE_GLX)
  #include <GL/glx.h>
 #endif
 #if defined(GLFW_EXPOSE_NATIVE_EGL)
  #include <EGL/egl.h>
 #endif
```

Whereas older versions have (taken from GLFW 3.1.2):

```C
#if defined(GLFW_EXPOSE_NATIVE_WGL)
 /* WGL is declared by windows.h */
#elif defined(GLFW_EXPOSE_NATIVE_NSGL)
 /* NSGL is declared by Cocoa.h */
#elif defined(GLFW_EXPOSE_NATIVE_GLX)
 #include <GL/glx.h>
#elif defined(GLFW_EXPOSE_NATIVE_EGL)
 #include <EGL/egl.h>
#else
 #error "No context API selected"
#endif
```

I will look into adding compatibility for older versions, however, you should update to GLFW 3.2 (or later).

Also, you should not be compiling as root.

**Comment by TechieAndroid** [comment]
Okay I figured that I should just compile it from source but used the package anyway. What's wrong with coming it as root? I recall it needed permission and I had no choice but to do it that way. In my experience, as long as your not stupid and running code with recursive properties, there's very little that could go wrong. I've personally never had any issues with it, aside from people harassing me about it. :/

**Comment by wacossusca34** [comment]
> Okay I figured that I should just compile it from source but used the package anyway.

What distro are you using that ships an outdated version of GLFW?

> What's wrong with coming it as root?

Bugs in the makefile (or other parts of the build process) can affect your entire system when running as root. While GLava's build system is plain simple, this is not the case for many other projects.

> as long as your not stupid and running code with recursive properties

Wildcard statements are used in my makefile. While that isn't recursive, it's not far from it. Run code from github with a less privilaged user, or better yet, a build user -- don't blindly trust me!

**Comment by TechieAndroid** [comment]
I had libglfw3 but removed it and compiled the source code from github.

now when I tried recompiling I get this:
`/usr/bin/ld: cannot find -lglfw
collect2: error: ld returned 1 exit status
Makefile:61: recipe for target 'glava' failed
make: *** [glava] Error 1
`
Also before removing that package it worked but looked pretty bad,  tried the config file but had limited success.
I want it to look like it did in your reddit post.

**Comment by wacossusca34** [comment]
> I had libglfw3 but removed it and compiled the source code from github.

You shouldn't need to compile GLFW from source unless your distro actually ships outdated versions 3.1.x and older. Also, please answer my question with regards to what distro you are using.

> /usr/bin/ld: cannot find -lglfw collect2: error: ld returned 1 exit status Makefile:61: recipe for target 'glava' failed make: *** [glava] Error 1

This looks like you failed to install the GLFW library you compiled correctly.

> Also before removing that package it worked but looked pretty bad

Can you give more details? 'looked pretty bad' doesn't help me.

**Comment by TechieAndroid** [comment]
Okay I'm running Ubuntu Studio LTS 16.04 with backports and pre-released updates, I changed from GDE to KDE. Earlier you started I needed to update GLFW (I had v3 then) so I removed that and compiled it from source. As far as looks I thought you could tell me if by default it lacks transparency, and when I change it to native it had no effect, also upon changing to radial it became really rough on the edges as if it lacked a filter or type of AA.

**Comment by wacossusca34** [comment]
> (I had v3 then) so I removed that and compiled it from source

You are misunderstanding. '3' is the major version, I need the full version string to understand your issue. (ie. `3.1.2`).

> also upon changing to radial it became really rough on the edges as if it lacked a filter or type of AA

I will incorperate alpha blending in the drawing code for `radial` later, and when I do implement it, it will only work for `xroot` transparency. Unfortunately that's just how it looks at the moment -- I only recently added the code for `xroot` transparency so I have yet to explore options with proper alpha blending.

`native` transparency will actually look worse once I do make use of the alpha layer better in shaders, this transparency mode is only for users that need _true transparency_, meaning they can see all the windows/animations/etc behind GLava's window contents.

**Comment by TechieAndroid** [comment]
3.1.2-3 It took me a while because the package manager was being obscure.

Well native, xroot and that other option didn't change the appearance when I was trying to change it.

**Comment by wacossusca34** [comment]
> Well native, xroot and that other option didn't change the appearance when I was trying to change it.

What are you trying to change? These are options for how the application handles transparency, they should look identical.

**Comment by TechieAndroid** [comment]
> What are you trying to change? These are options for how the application handles transparency, they should look identical.

> by default it lacks transparency
I meant that the window is black.
None of the options provided (yes even the default ones) make it look clear. I don't know why your making it so difficult, I've been clear.

**Comment by TechieAndroid** [comment]
Can't get much clearer than a picture... [https://imgur.com/VBML1Th.png](url) You can see my wallpaper around the edges, that gives you an idea of the surface area that is black.

**Comment by wacossusca34** [comment]
I'll provide one last explanation of what these options do:

`native` uses an existing **compositor** (such as compton) to provide transparency, and requires GLava to be _compiled_ against GLFW 3.3 or later to function properly.

`xroot` takes the _root X11 window_ and copies its contents for GLava itself to use as the background, and is generally faster than `native` transparency, but can cause issues when the desktop background isn't actually the root window (or if you want true transparency).

`native` transparency not working is almost certainly a mistake on your behalf. `xroot` not working is probably an environment-specific problem (WM-specific, or using other software to display your wallpaper).

> I don't know why your making it so difficult, I've been clear.

No, you have not. When reporting issues/bugs with software, you have a responsibility to provide as much relevant information as possible. If you explain _everything_ you are doing to encounter an issue, I can reproduce it myself and then further diagnose the issue -- I can't do that with the information you have given me thus far.

**Comment by TechieAndroid** [comment]
3.1.2-3 seems to be for the moment the only version working properly on my system. I will try to compile it again (although they had vague instructions for compiling in GNU/Linux and what dependencies were required ect...). You'll probably laugh at this but I'd like it if I could just compile something and it work, and then I wouldn't have to compile all the programs required to compile this one (otherwise I might as well switch to Gentoo and compile my kernel and all my applications), I have a limited background in C++, so I don't know what you expect me to know how to do.

**Comment by wacossusca34** [comment]
I urge you to wait until GLava has a stable release and an Ubuntu/Debian package you can install instead.

**Comment by wacossusca34** [comment]
> upon changing to radial it became really rough on the edges as if it lacked a filter or type of AA

Just an update, [this recent commit](https://github.com/wacossusca34/glava/commit/02aba3db9276f1d5d222308d42677b325bd7988b) added aliasing functionality to the `radial` module which makes it look _much_ better and addresses this complaint.

Here is a comparison between old and new versions (zoom in on the red `radial` instances):

![Demo](https://i.imgur.com/SVhMCaN.png)

Note `native` transparency will not provide aliasing, as it would require the compositor itself to perform alpha blending (which I am not sure is even possible).
