### ISSUE TITLE
Parse and include system defaults for module configs

### ISSUE THREAD

**Issue by wacossusca34** [wacossusca34/glava#74]
See [this comment I made earlier](https://github.com/wacossusca34/glava/pull/73#issuecomment-433256283) for some context. Adding new options to existing modules unfortunately breaks local configurations upon `make install` (or package updates), due to how modules are symlinked in.

This feature would add a `#config` directive to replace `#include ":config_path"` in module sources that intelligently handles defines.

**Comment by Aaahh** [comment]
https://github.com/wacossusca34/glava/pull/75

**Comment by coderobe** [comment]
@Aaahh That's not quite the solution proposed here

**Comment by wacossusca34** [comment]
I implemented this in a different way:

* First, I wrote a workaround in GLava's GLSL preprocessor to allow `#define` to work with existing macros. It works by emitting the same boilerplate that #75 would have manually added. **Note that this behavior does not exist for function-like macros (`#define foo() ...`), and thus should be avoided in module configurations.**

* I then wrote a new piece of syntax for `#include` in macros: `@`. It works just like the `:` path specifier, but instead of resolving to the current configuration directory (usually `~/.config/glava`), it resolves to the _top level_ directory, which in regular builds is the system directory.

With these two new changes, you can now do:

```GLSL
/* system (default) values */
#include "@module.glsl"
/* user values */
#include ":module.glsl"
```

Note that in standalone builds, or GLava instances without a `.config` entry, these two paths will be the same.

Since this commit only makes changes to module sources, it should be backwards compatible.
