### ISSUE TITLE
glfw

### ISSUE THREAD

**Issue by jubalh** [wacossusca34/glava#81]
Sorry to open an issue for this. But I wondered: what is the advantage to compile with `ENABLE_GLFW=1` ?

**Comment by wacossusca34** [comment]
GLava was initially written with GLFW for window instantiation. This was much simpler, but GLFW abstracts out a lot of details with the X11 window that was easier to work with by using Xlib and GLX directly.

Namely, transparency support in GLFW is a fairly recent change and many distributions have yet to adopt the updated library. Being able to process the X11 event queue is also important, which I can't do with GLFW.

I keep GLFW support in the code in the event of someone attempting an OSX or Windows port, in which it will keep window instantiation out of the way. There's no real reason to actually enable it on Linux except perhaps on some Wayland compositors.
