### ISSUE TITLE
Makefile fails with old GCC/zsh

### ISSUE THREAD

**Issue by InvisibleRasta** [wacossusca34/glava#84]
CFLAGS="-march=native" make                                                                                        
/bin/sh: 1: [[: not found
cc: error: unrecognized command line option ‘-Wstringop-overflow=0’; did you mean ‘-Wstrict-overflow=’?
Makefile:93: recipe for target 'glava.o' failed
make: *** [glava.o] Error 1

**Comment by coderobe** [comment]
What system is this on? Looks like your cc is old, and your make shell is sh instead of bash?

**Comment by wacossusca34** [comment]
You can remove the flag from the `Makefile` for the time being. I'm not sure why you are getting that error unless `cc` isn't actually `gcc`.

**Comment by InvisibleRasta** [comment]
well im running debian stretch fully updated. i t shouldnt be that old right?

**Comment by wacossusca34** [comment]
Closing due to this being a non-issue.
